const productos = [
    {
        id: '1',
        tittle : 'Iphone 7',
        brand: 'Apple',
        price : '90000',
        image : 'iphone13Detail1.png',
        image2: 'iphone13Detail2.png',
        image3: 'iphone13Detail3.png',
        image4: 'iphone13Detail4.png',
        image5: 'iphone13Detail5.png',
        description: 'Celular Iphone 7 4g 128gb Ram 200hz SM-A344hnqwO',
        category: 'celulares',
        stock: 4
    },
    {
        id: '2',
        tittle : 'Samsung J7',
        brand: 'Samsung',
        price : '80000',
        image:'samsungj71.png',
        image2: 'samsungj72.png',
        image3: 'samsungj73.png',
        image4: 'samsungj74.png',
        image5: 'samsungj75.png',
        description: 'Celular Samsung J7 4g 16gb 1.5GHz SM-J700MZKATCE',
        category: 'celulares',
        stock: 6
        
    },
    {
        id: '3',
        tittle : 'TV Samsung 4k',
        brand : 'Samsung',
        price : '140000',
        image: 'TvSamsung4k.png',
        image2: 'TvSamsung4k.png',
        image3: 'TvSamsung4k.png',
        image4: 'TvSamsung4k.png',
        image5:'TvSamsung4k.png',
        description: 'TV Samsung 4k HD 1440 3D SM-A344hnqwO',
        category: 'televisores',
        stock: 2
    },
    {
        id: '4',
        tittle : 'PlayStation 5',
        brand : 'Sony',
        price : '200000',
        image:'Playstation5.png',
        image2: 'Playstation5.png',
        image3: 'Playstation5.png',
        image4: 'Playstation5.png',
        image5:'Playstation5.png',
        description: 'PlayStation 5 240gb 120 RAM 200hz SM-A344hnqwO',
        category: 'consolas',
        stock: 10
    },
    {
        id: '5',
        tittle : 'Samsung J7',
        brand: 'Samsung',
        price : '80000',
        image:'samsungj71.png',
        image2: 'samsungj72.png',
        image3: 'samsungj73.png',
        image4: 'samsungj74.png',
        image5: 'samsungj75.png',
        description: 'Celular Samsung J7 4g 16gb 1.5GHz SM-J700MZKATCE',
        category: 'celulares',
        stock: 6
        
    },
    {
        id: '6',
        tittle : 'TV Samsung 4k',
        brand : 'Samsung',
        price : '140000',
        image: 'TvSamsung4k.png',
        image2: 'TvSamsung4k.png',
        image3: 'TvSamsung4k.png',
        image4: 'TvSamsung4k.png',
        image5:'TvSamsung4k.png',
        description: 'TV Samsung 4k HD 1440 3D SM-A344hnqwO',
        category: 'televisores',
        stock: 2
    },
    {
        id: '7',
        tittle : 'TV Samsung 4k',
        brand : 'Samsung',
        price : '140000',
        image: 'TvSamsung4k.png',
        image2: 'TvSamsung4k.png',
        image3: 'TvSamsung4k.png',
        image4: 'TvSamsung4k.png',
        image5:'TvSamsung4k.png',
        description: 'TV Samsung 4k HD 1440 3D SM-A344hnqwO',
        category: 'televisores',
        stock: 2
    },
    {
        id: '8',
        tittle : 'TV Samsung 4k',
        brand : 'Samsung',
        price : '140000',
        image: 'TvSamsung4k.png',
        image2: 'TvSamsung4k.png',
        image3: 'TvSamsung4k.png',
        image4: 'TvSamsung4k.png',
        image5:'TvSamsung4k.png',
        description: 'TV Samsung 4k HD 1440 3D SM-A344hnqwO',
        category: 'televisores',
        stock: 2
    },
    {
        id: '9',
        tittle : 'TV Samsung 4k',
        brand : 'Samsung',
        price : '140000',
        image: 'TvSamsung4k.png',
        image2: 'TvSamsung4k.png',
        image3: 'TvSamsung4k.png',
        image4: 'TvSamsung4k.png',
        image5:'TvSamsung4k.png',
        description: 'TV Samsung 4k HD 1440 3D SM-A344hnqwO',
        category: 'televisores',
        stock: 2
    },
]

export default productos